package com.ess;
// Generated Jul 30, 2014 10:31:46 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdminDetails generated by hbm2java
 */
@Entity
@Table(name="admin_details"
    ,catalog="expert_support_system"
)
public class AdminDetails  implements java.io.Serializable {


     private Integer loginId;
     private String passwd;
     private String grp;
     private Integer workingHours;
     private Integer noOfTickets;
     private String solverName;
     private String category;
     private String issue;
     private String clientName;

    public AdminDetails() {
    }

	
    public AdminDetails(String passwd, String grp, String solverName, String category, String issue, String clientName) {
        this.passwd = passwd;
        this.grp = grp;
        this.solverName = solverName;
        this.category = category;
        this.issue = issue;
        this.clientName = clientName;
    }
    public AdminDetails(String passwd, String grp, Integer workingHours, Integer noOfTickets, String solverName, String category, String issue, String clientName) {
       this.passwd = passwd;
       this.grp = grp;
       this.workingHours = workingHours;
       this.noOfTickets = noOfTickets;
       this.solverName = solverName;
       this.category = category;
       this.issue = issue;
       this.clientName = clientName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Login_Id", unique=true, nullable=false)
    public Integer getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    
    @Column(name="Passwd", nullable=false, length=30)
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    
    @Column(name="Grp", nullable=false, length=30)
    public String getGrp() {
        return this.grp;
    }
    
    public void setGrp(String grp) {
        this.grp = grp;
    }

    
    @Column(name="Working_Hours")
    public Integer getWorkingHours() {
        return this.workingHours;
    }
    
    public void setWorkingHours(Integer workingHours) {
        this.workingHours = workingHours;
    }

    
    @Column(name="No_of_tickets")
    public Integer getNoOfTickets() {
        return this.noOfTickets;
    }
    
    public void setNoOfTickets(Integer noOfTickets) {
        this.noOfTickets = noOfTickets;
    }

    
    @Column(name="Solver_Name", nullable=false, length=30)
    public String getSolverName() {
        return this.solverName;
    }
    
    public void setSolverName(String solverName) {
        this.solverName = solverName;
    }

    
    @Column(name="Category", nullable=false, length=30)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="Issue", nullable=false, length=30)
    public String getIssue() {
        return this.issue;
    }
    
    public void setIssue(String issue) {
        this.issue = issue;
    }

    
    @Column(name="Client_Name", nullable=false, length=30)
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }




}


