package com.ess;
// Generated Jul 30, 2014 10:31:46 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Announcement generated by hbm2java
 */
@Entity
@Table(name="announcement"
    ,catalog="expert_support_system"
)
public class Announcement  implements java.io.Serializable {


     private Integer annId;
     private String annForGrp;
     private Date issuedDate;
     private String topic;
     private String announcement;

    public Announcement() {
    }

    public Announcement(String annForGrp, Date issuedDate, String topic, String announcement) {
       this.annForGrp = annForGrp;
       this.issuedDate = issuedDate;
       this.topic = topic;
       this.announcement = announcement;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Ann_Id", unique=true, nullable=false)
    public Integer getAnnId() {
        return this.annId;
    }
    
    public void setAnnId(Integer annId) {
        this.annId = annId;
    }

    
    @Column(name="Ann_for_Grp", nullable=false, length=30)
    public String getAnnForGrp() {
        return this.annForGrp;
    }
    
    public void setAnnForGrp(String annForGrp) {
        this.annForGrp = annForGrp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Issued_Date", nullable=false, length=10)
    public Date getIssuedDate() {
        return this.issuedDate;
    }
    
    public void setIssuedDate(Date issuedDate) {
        this.issuedDate = issuedDate;
    }

    
    @Column(name="Topic", nullable=false, length=40)
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }

    
    @Column(name="Announcement", nullable=false, length=100)
    public String getAnnouncement() {
        return this.announcement;
    }
    
    public void setAnnouncement(String announcement) {
        this.announcement = announcement;
    }




}


