package com.ess;
// Generated Jul 30, 2014 10:31:46 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnswerDetails generated by hbm2java
 */
@Entity
@Table(name="answer_details"
    ,catalog="expert_support_system"
)
public class AnswerDetails  implements java.io.Serializable {


     private int ticketId;
     private LoginDetails loginDetails;
     private ClientDetails clientDetails;
     private String category;
     private String solverName;
     private String issue;
     private String solution;

    public AnswerDetails() {
    }

    public AnswerDetails(int ticketId, LoginDetails loginDetails, ClientDetails clientDetails, String category, String solverName, String issue, String solution) {
       this.ticketId = ticketId;
       this.loginDetails = loginDetails;
       this.clientDetails = clientDetails;
       this.category = category;
       this.solverName = solverName;
       this.issue = issue;
       this.solution = solution;
    }
   
     @Id 

    
    @Column(name="Ticket_Id", unique=true, nullable=false)
    public int getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(int ticketId) {
        this.ticketId = ticketId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Login_Id", nullable=false)
    public LoginDetails getLoginDetails() {
        return this.loginDetails;
    }
    
    public void setLoginDetails(LoginDetails loginDetails) {
        this.loginDetails = loginDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Client_Id", nullable=false)
    public ClientDetails getClientDetails() {
        return this.clientDetails;
    }
    
    public void setClientDetails(ClientDetails clientDetails) {
        this.clientDetails = clientDetails;
    }

    
    @Column(name="Category", nullable=false, length=30)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="Solver Name", nullable=false, length=30)
    public String getSolverName() {
        return this.solverName;
    }
    
    public void setSolverName(String solverName) {
        this.solverName = solverName;
    }

    
    @Column(name="Issue", nullable=false, length=30)
    public String getIssue() {
        return this.issue;
    }
    
    public void setIssue(String issue) {
        this.issue = issue;
    }

    
    @Column(name="Solution", nullable=false, length=200)
    public String getSolution() {
        return this.solution;
    }
    
    public void setSolution(String solution) {
        this.solution = solution;
    }




}


