package com.ess;
// Generated Jul 30, 2014 10:31:46 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssestsDetails generated by hbm2java
 */
@Entity
@Table(name="assests_details"
    ,catalog="expert_support_system"
)
public class AssestsDetails  implements java.io.Serializable {


     private Integer assetId;
     private String assestName;
     private Integer quantity;
     private BigDecimal cost;

    public AssestsDetails() {
    }

	
    public AssestsDetails(String assestName) {
        this.assestName = assestName;
    }
    public AssestsDetails(String assestName, Integer quantity, BigDecimal cost) {
       this.assestName = assestName;
       this.quantity = quantity;
       this.cost = cost;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Asset_Id", unique=true, nullable=false)
    public Integer getAssetId() {
        return this.assetId;
    }
    
    public void setAssetId(Integer assetId) {
        this.assetId = assetId;
    }

    
    @Column(name="Assest_Name", nullable=false, length=30)
    public String getAssestName() {
        return this.assestName;
    }
    
    public void setAssestName(String assestName) {
        this.assestName = assestName;
    }

    
    @Column(name="Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="Cost", precision=10)
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }




}


