package com.ess;
// Generated Jul 30, 2014 10:31:46 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AutoResponder generated by hbm2java
 */
@Entity
@Table(name="auto_responder"
    ,catalog="expert_support_system"
)
public class AutoResponder  implements java.io.Serializable {


     private Integer autoResponderId;
     private String category;
     private String issue;
     private String solution;
     private String author;
     private Date dateOfArticle;
     private String advMsg;

    public AutoResponder() {
    }

    public AutoResponder(String category, String issue, String solution, String author, Date dateOfArticle, String advMsg) {
       this.category = category;
       this.issue = issue;
       this.solution = solution;
       this.author = author;
       this.dateOfArticle = dateOfArticle;
       this.advMsg = advMsg;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="auto_responder_Id", unique=true, nullable=false)
    public Integer getAutoResponderId() {
        return this.autoResponderId;
    }
    
    public void setAutoResponderId(Integer autoResponderId) {
        this.autoResponderId = autoResponderId;
    }

    
    @Column(name="Category", nullable=false, length=45)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="Issue", nullable=false, length=30)
    public String getIssue() {
        return this.issue;
    }
    
    public void setIssue(String issue) {
        this.issue = issue;
    }

    
    @Column(name="Solution", nullable=false, length=200)
    public String getSolution() {
        return this.solution;
    }
    
    public void setSolution(String solution) {
        this.solution = solution;
    }

    
    @Column(name="Author", nullable=false, length=30)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date_of_Article", nullable=false, length=10)
    public Date getDateOfArticle() {
        return this.dateOfArticle;
    }
    
    public void setDateOfArticle(Date dateOfArticle) {
        this.dateOfArticle = dateOfArticle;
    }

    
    @Column(name="Adv_MSG", nullable=false, length=100)
    public String getAdvMsg() {
        return this.advMsg;
    }
    
    public void setAdvMsg(String advMsg) {
        this.advMsg = advMsg;
    }




}


