package com.ess;
// Generated Jul 30, 2014 10:31:46 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CancelTicket generated by hbm2java
 */
@Entity
@Table(name="cancel_ticket"
    ,catalog="expert_support_system"
)
public class CancelTicket  implements java.io.Serializable {


     private int ticketId;
     private ClientDetails clientDetails;
     private String issue;
     private String priority;
     private String solverName;
     private String category;
     private String reason;
     private Date cancelationDate;

    public CancelTicket() {
    }

    public CancelTicket(int ticketId, ClientDetails clientDetails, String issue, String priority, String solverName, String category, String reason, Date cancelationDate) {
       this.ticketId = ticketId;
       this.clientDetails = clientDetails;
       this.issue = issue;
       this.priority = priority;
       this.solverName = solverName;
       this.category = category;
       this.reason = reason;
       this.cancelationDate = cancelationDate;
    }
   
     @Id 

    
    @Column(name="Ticket_Id", unique=true, nullable=false)
    public int getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(int ticketId) {
        this.ticketId = ticketId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Client_Id", nullable=false)
    public ClientDetails getClientDetails() {
        return this.clientDetails;
    }
    
    public void setClientDetails(ClientDetails clientDetails) {
        this.clientDetails = clientDetails;
    }

    
    @Column(name="Issue", nullable=false, length=30)
    public String getIssue() {
        return this.issue;
    }
    
    public void setIssue(String issue) {
        this.issue = issue;
    }

    
    @Column(name="Priority", nullable=false, length=30)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    
    @Column(name="Solver_Name", nullable=false, length=30)
    public String getSolverName() {
        return this.solverName;
    }
    
    public void setSolverName(String solverName) {
        this.solverName = solverName;
    }

    
    @Column(name="Category", nullable=false, length=30)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="Reason", nullable=false, length=50)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Cancelation_Date", nullable=false, length=10)
    public Date getCancelationDate() {
        return this.cancelationDate;
    }
    
    public void setCancelationDate(Date cancelationDate) {
        this.cancelationDate = cancelationDate;
    }




}


