package com.ess;
// Generated Jul 30, 2014 10:31:46 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeeDetails generated by hbm2java
 */
@Entity
@Table(name="fee_details"
    ,catalog="expert_support_system"
)
public class FeeDetails  implements java.io.Serializable {


     private int clientId;
     private String issue;
     private String priority;
     private BigDecimal charges;

    public FeeDetails() {
    }

    public FeeDetails(int clientId, String issue, String priority, BigDecimal charges) {
       this.clientId = clientId;
       this.issue = issue;
       this.priority = priority;
       this.charges = charges;
    }
   
     @Id 

    
    @Column(name="Client_Id", unique=true, nullable=false)
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="Issue", nullable=false, length=30)
    public String getIssue() {
        return this.issue;
    }
    
    public void setIssue(String issue) {
        this.issue = issue;
    }

    
    @Column(name="Priority", nullable=false, length=30)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    
    @Column(name="Charges", nullable=false, precision=10)
    public BigDecimal getCharges() {
        return this.charges;
    }
    
    public void setCharges(BigDecimal charges) {
        this.charges = charges;
    }




}


