package com.ess;
// Generated Jul 30, 2014 10:31:46 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupDetails generated by hbm2java
 */
@Entity
@Table(name="group_details"
    ,catalog="expert_support_system"
)
public class GroupDetails  implements java.io.Serializable {


     private int groupNumber;
     private LoginDetails loginDetails;
     private String name;
     private String specialization;
     private String passwd;

    public GroupDetails() {
    }

    public GroupDetails(int groupNumber, LoginDetails loginDetails, String name, String specialization, String passwd) {
       this.groupNumber = groupNumber;
       this.loginDetails = loginDetails;
       this.name = name;
       this.specialization = specialization;
       this.passwd = passwd;
    }
   
     @Id 

    
    @Column(name="Group_Number", unique=true, nullable=false)
    public int getGroupNumber() {
        return this.groupNumber;
    }
    
    public void setGroupNumber(int groupNumber) {
        this.groupNumber = groupNumber;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Login_Id", nullable=false)
    public LoginDetails getLoginDetails() {
        return this.loginDetails;
    }
    
    public void setLoginDetails(LoginDetails loginDetails) {
        this.loginDetails = loginDetails;
    }

    
    @Column(name="Name", nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Specialization", nullable=false, length=30)
    public String getSpecialization() {
        return this.specialization;
    }
    
    public void setSpecialization(String specialization) {
        this.specialization = specialization;
    }

    
    @Column(name="Passwd", nullable=false, length=30)
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }




}


