package com.ess;
// Generated Jul 30, 2014 10:31:46 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TicketDetails generated by hbm2java
 */
@Entity
@Table(name="ticket_details"
    ,catalog="expert_support_system"
)
public class TicketDetails  implements java.io.Serializable {


     private Integer ticketId;
     private LoginDetails loginDetails;
     private String category;
     private String priority;
     private String issue;
     private String status;
     private Set<SessionDetails> sessionDetailses = new HashSet<SessionDetails>(0);

    public TicketDetails() {
    }

	
    public TicketDetails(LoginDetails loginDetails, String category, String priority, String issue, String status) {
        this.loginDetails = loginDetails;
        this.category = category;
        this.priority = priority;
        this.issue = issue;
        this.status = status;
    }
    public TicketDetails(LoginDetails loginDetails, String category, String priority, String issue, String status, Set<SessionDetails> sessionDetailses) {
       this.loginDetails = loginDetails;
       this.category = category;
       this.priority = priority;
       this.issue = issue;
       this.status = status;
       this.sessionDetailses = sessionDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Ticket_Id", unique=true, nullable=false)
    public Integer getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Login_Id", nullable=false)
    public LoginDetails getLoginDetails() {
        return this.loginDetails;
    }
    
    public void setLoginDetails(LoginDetails loginDetails) {
        this.loginDetails = loginDetails;
    }

    
    @Column(name="Category", nullable=false, length=30)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="Priority", nullable=false, length=30)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    
    @Column(name="Issue", nullable=false, length=30)
    public String getIssue() {
        return this.issue;
    }
    
    public void setIssue(String issue) {
        this.issue = issue;
    }

    
    @Column(name="Status", nullable=false, length=30)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticketDetails")
    public Set<SessionDetails> getSessionDetailses() {
        return this.sessionDetailses;
    }
    
    public void setSessionDetailses(Set<SessionDetails> sessionDetailses) {
        this.sessionDetailses = sessionDetailses;
    }




}


